[project]
name = "pdm"
version = "4.5.7"
dependencies = [
  "requests==2.31.0"
]
requires-python = ">=3.8"
readme = "README.md"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
