[project]
name = "pdm"
version = "4.5.6"
dependencies = [
  "requests==2.29.0"
]
requires-python = ">=3.8"
readme = "README.md"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
